import Header from '@/components/ui/Header';
import Banner from '@/components/ui/Banner';
import Footer from '@/components/ui/Footer';

export default function License() {
    return (
        <div className="min-h-screen bg-cream font-sans text-ink">
            <Banner />
            <Header />
            <main className="max-w-4xl mx-auto px-6 py-12 lg:py-20">
                <h1 className="text-4xl font-bold mb-8">Commercial License</h1>
                <div className="prose prose-lg prose-headings:font-bold prose-headings:text-ink prose-p:text-ink/80 max-w-none">
                    <p>Last Updated: {new Date().toLocaleDateString()}</p>

                    <p>
                        This Commercial License governs the use of the mockup images generated using Nano Banana Pro.
                    </p>

                    <h3>1. Grant of License</h3>
                    <p>
                        Subject to your compliance with the Terms of Service, Nano Banana Pro grants you a perpetual, non-exclusive, worldwide, royalty-free license to use, reproduce, modify, and display the mockup images generated by the platform for both personal and commercial purposes.
                    </p>

                    <h3>2. Permitted Uses</h3>
                    <p>You may use the generated mockups for:</p>
                    <ul>
                        <li>E-commerce product listings (Etsy, Shopify, Amazon, etc.).</li>
                        <li>Social media marketing and advertising.</li>
                        <li>Client presentations and portfolios.</li>
                        <li>Website and print materials.</li>
                    </ul>

                    <h3>3. Restrictions</h3>
                    <p>You may NOT:</p>
                    <ul>
                        <li>Resell, sub-license, or redistribute the generated mockup images as standalone stock photography or digital assets.</li>
                        <li>Claim ownership of the underlying 3D models or base photography provided by Nano Banana Pro.</li>
                        <li>Use the images in connection with illegal, defamatory, or hateful content.</li>
                    </ul>

                    <h3>4. Termination</h3>
                    <p>
                        This license is effective until terminated. Your rights under this license will terminate automatically without notice if you fail to comply with any of its terms.
                    </p>
                </div>
            </main>
            <Footer />
        </div>
    );
}
