import { GoogleGenerativeAI } from '@google/generative-ai';

// Initialize the Google Gen AI Client
const apiKey = process.env.GEMINI_API_KEY;

// Using Copié-Collé (Gemini 3 Pro Image)
const modelId = 'gemini-3-pro-image-preview';

export const generateMockup = async (
    baseImageUrl: string,
    logoUrl: string,
    prompt: string,
    aspectRatio: string = '1:1',
    imageSize: string = '1K'
) => {
    if (!apiKey) {
        throw new Error("Missing GEMINI_API_KEY in environment variables.");
    }

    try {
        console.log(`Calling Copié-Collé (Gemini API) with Aspect Ratio: ${aspectRatio} and Size: ${imageSize}...`);

        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({
            model: modelId,
            generationConfig: {
                // Gemini 3 Pro Image requires both TEXT and IMAGE modalities
                responseModalities: ["TEXT", "IMAGE"],
                imageConfig: {
                    aspectRatio: aspectRatio,
                    imageSize: imageSize
                }
            } as any
        });

        // Helper to fetch and convert URL to Base64
        const urlToPart = async (url: string) => {
            const response = await fetch(url);
            const arrayBuffer = await response.arrayBuffer();
            const base64 = Buffer.from(arrayBuffer).toString('base64');
            const mimeType = response.headers.get('content-type') || 'image/png';
            return {
                inlineData: {
                    data: base64,
                    mimeType
                }
            };
        };

        console.log("Fetching image assets...");
        const [baseImagePart, logoImagePart] = await Promise.all([
            urlToPart(baseImageUrl),
            urlToPart(logoUrl)
        ]);

        // 1. Prepare Inputs
        // The 'prompt' variable contains either the custom product instruction or a default instruction.
        const fullPrompt = `Generate a photorealistic product shot. ${prompt} Important: Keep the provided design/logo unchanged, preserving its colors, text, and details exactly as they appear. Apply it realistically to the surface. Ensure high quality, detailed texture, and realistic lighting.`;

        console.log("Sending request to model with images...");
        // 2. Call API
        // Pass the text prompt AND the image parts
        const result = await model.generateContent([
            fullPrompt,
            baseImagePart,
            logoImagePart
        ]);
        const response = await result.response;

        // 3. Extract Image
        // We'll inspect the response structure. 
        // If it's standard text generation, it returns text.
        // If it's image generation, it usually returns inlineData.

        console.log("Model response candidates:", response.candidates);

        const parts = response.candidates?.[0]?.content?.parts;
        const imagePart = parts?.find((part: any) => part.inlineData);

        if (!imagePart || !imagePart.inlineData) {
            // If no image part, maybe it returned text saying it can't do it?
            const textPart = parts?.find((part: any) => part.text);
            if (textPart) {
                console.warn("Model returned text instead of image:", textPart.text);
                throw new Error("Model returned text: " + textPart.text);
            }
            throw new Error("No image generated by the model.");
        }

        const base64Image = imagePart.inlineData.data;
        const mimeType = imagePart.inlineData.mimeType || 'image/png';

        return {
            success: true,
            mockUrl: `data:${mimeType};base64,${base64Image}`
        };

    } catch (error: any) {
        console.error("Gemini API Error:", error);
        return {
            success: false, // Let the frontend show the error
            error: error.message || "Unknown error"
        };
    }
};

export const analyzeMockupImage = async (imageUrl: string, productType: 'mockup' | 'scene' = 'mockup', productNameHint?: string, keywordsHint?: string) => {
    if (!apiKey) {
        throw new Error("Missing GEMINI_API_KEY in environment variables.");
    }

    try {
        const genAI = new GoogleGenerativeAI(apiKey);
        // Use Gemini 3 Pro Preview as requested
        const model = genAI.getGenerativeModel({ model: "gemini-3-pro-preview" });

        // Fetch image and convert to base64
        const response = await fetch(imageUrl);
        const arrayBuffer = await response.arrayBuffer();
        const base64 = Buffer.from(arrayBuffer).toString('base64');
        const mimeType = response.headers.get('content-type') || 'image/png';

        let prompt = '';

        const hintContext = productNameHint ? `Context/Product Name: "${productNameHint}".` : '';
        const keywordContext = keywordsHint ? `Keywords to include: "${keywordsHint}".` : '';

        if (productType === 'scene') {
            prompt = `
                Analyze this background scene image and generate SEO-optimized details for it.
                ${hintContext}
                ${keywordContext}
                Return ONLY a JSON object with the following fields:
                - title: A catchy, descriptive title (e.g., "Cozy Wooden Desk Scene with Coffee").
                - description: A detailed, SEO-friendly description highlighting the lighting, mood, and available space for product placement.
                - tags: A comma-separated string of 5-10 relevant keywords (e.g., "desk, wood, coffee, cozy, morning, workspace").
                - slug: A URL-friendly slug based on the title (e.g., "cozy-wooden-desk-scene").
                - custom_prompt: A short instruction for an AI to place a product into this scene (e.g., "Place the product on the center of the wooden desk, matching the warm morning lighting and soft shadows.").
                
                Do not include markdown formatting like \`\`\`json. Just the raw JSON string.
            `;
        } else {
            prompt = `
                Analyze this product mockup image and generate SEO-optimized details for it.
                ${hintContext}
                ${keywordContext}
                Return ONLY a JSON object with the following fields:
                - title: A catchy, descriptive title (e.g., "Minimalist White Hoodie Mockup on Hanger").
                - description: A detailed, SEO-friendly description highlighting the setting, lighting, and vibe.
                - tags: A comma-separated string of 5-10 relevant keywords (e.g., "hoodie, streetwear, hanger, white, minimalist").
                - slug: A URL-friendly slug based on the title (e.g., "minimalist-white-hoodie-hanger").
                - custom_prompt: A short instruction for an AI to place a design on this product (e.g., "Place the design on the center chest area, maintaining the fabric wrinkles and lighting.").
                
                Do not include markdown formatting like \`\`\`json. Just the raw JSON string.
            `;
        }

        const result = await model.generateContent([
            prompt,
            {
                inlineData: {
                    data: base64,
                    mimeType
                }
            }
        ]);

        const text = result.response.text();

        // Clean up markdown if present
        const cleanText = text.replace(/```json/g, '').replace(/```/g, '').trim();

        return JSON.parse(cleanText);

    } catch (error: any) {
        console.error("Gemini Analysis Error:", error);
        throw new Error("Failed to analyze image: " + error.message);
    }
};

export const generateScene = async (
    baseImageUrl: string,
    prompt: string
) => {
    if (!apiKey) {
        throw new Error("Missing GEMINI_API_KEY in environment variables.");
    }

    try {
        console.log(`Calling Copié-Collé (Gemini Scene Generation)...`);

        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({
            model: modelId, // Use same model: gemini-3-pro-image-preview
            generationConfig: {
                responseModalities: ["IMAGE"], // We only want the image
                imageConfig: {
                    aspectRatio: "1:1", // Default to square for now
                    imageSize: "1K"
                }
            } as any
        });

        // Fetch and convert Base Image
        const response = await fetch(baseImageUrl);
        const arrayBuffer = await response.arrayBuffer();
        const base64 = Buffer.from(arrayBuffer).toString('base64');
        const mimeType = response.headers.get('content-type') || 'image/png';

        const baseImagePart = {
            inlineData: {
                data: base64,
                mimeType
            }
        };

        // Construct Prompt
        const fullPrompt = `
            Take this blank product image and place it into a professional, photorealistic scene.
            ${prompt}
            Important: Keep the product itself (shape, material) exactly as is, just change the background and lighting to match the scene.
            Ensure high quality, detailed texture, and realistic lighting.
        `;

        console.log("Sending scene generation request...");
        const result = await model.generateContent([
            fullPrompt,
            baseImagePart
        ]);
        const apiResponse = await result.response;

        const parts = apiResponse.candidates?.[0]?.content?.parts;
        const imagePart = parts?.find((part: any) => part.inlineData);

        if (!imagePart || !imagePart.inlineData) {
            throw new Error("No image generated by the model.");
        }

        const base64Image = imagePart.inlineData.data;
        const resMimeType = imagePart.inlineData.mimeType || 'image/png';

        return {
            success: true,
            mockUrl: `data:${resMimeType};base64,${base64Image}`
        };

    } catch (error: any) {
        console.error("Gemini Scene Gen Error:", error);
        return {
            success: false,
            error: error.message || "Unknown error"
        };
    }
};

export const generateProductPlacement = async (
    sceneImageUrl: string,
    productImageUrl: string,
    prompt: string,
    aspectRatio: string = '1:1',
    imageSize: string = '1K'
) => {
    if (!apiKey) {
        throw new Error("Missing GEMINI_API_KEY in environment variables.");
    }

    try {
        console.log(`Calling Copié-Collé (Product Placement) with Aspect Ratio: ${aspectRatio} and Size: ${imageSize}...`);

        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({
            model: modelId,
            generationConfig: {
                responseModalities: ["TEXT", "IMAGE"],
                imageConfig: {
                    aspectRatio: aspectRatio,
                    imageSize: imageSize
                }
            } as any
        });

        // Helper to fetch and convert URL to Base64
        const urlToPart = async (url: string) => {
            const response = await fetch(url);
            const arrayBuffer = await response.arrayBuffer();
            const base64 = Buffer.from(arrayBuffer).toString('base64');
            const mimeType = response.headers.get('content-type') || 'image/png';
            return {
                inlineData: {
                    data: base64,
                    mimeType
                }
            };
        };

        console.log("Fetching image assets...");
        const [sceneImagePart, productImagePart] = await Promise.all([
            urlToPart(sceneImageUrl),
            urlToPart(productImageUrl)
        ]);

        // Construct Prompt for Product Placement
        const fullPrompt = `
            Generate a photorealistic product photography shot.
            ${prompt}
            Task: Place the provided product object into the provided scene background.
            Important:
            1. The product object (from the second image) must be the main focus. Keep its shape, label, and details exactly as they are.
            2. The background scene (from the first image) should be used as the environment.
            3. Blend the product naturally into the scene with correct perspective, lighting, shadows, and reflections.
            4. Ensure high quality, detailed texture, and realistic lighting.
        `;

        console.log("Sending request to model with images...");
        const result = await model.generateContent([
            fullPrompt,
            sceneImagePart,
            productImagePart
        ]);
        const response = await result.response;

        console.log("Model response candidates:", response.candidates);

        const parts = response.candidates?.[0]?.content?.parts;
        const imagePart = parts?.find((part: any) => part.inlineData);

        if (!imagePart || !imagePart.inlineData) {
            const textPart = parts?.find((part: any) => part.text);
            if (textPart) {
                console.warn("Model returned text instead of image:", textPart.text);
                throw new Error("Model returned text: " + textPart.text);
            }
            throw new Error("No image generated by the model.");
        }

        const base64Image = imagePart.inlineData.data;
        const mimeType = imagePart.inlineData.mimeType || 'image/png';

        return {
            success: true,
            mockUrl: `data:${mimeType};base64,${base64Image}`
        };

    } catch (error: any) {
        console.error("Gemini Product Placement Error:", error);
        return {
            success: false,
            error: error.message || "Unknown error"
        };
    }
};
