import { GoogleGenerativeAI } from '@google/generative-ai';

// Initialize the Google Gen AI Client
const apiKey = process.env.GEMINI_API_KEY;

// Using Nano Banana Pro (Gemini 3 Pro Image)
const modelId = 'gemini-3-pro-image-preview';

export const generateMockup = async (
    baseImageUrl: string,
    logoUrl: string,
    prompt: string,
    aspectRatio: string = '1:1'
) => {
    if (!apiKey) {
        throw new Error("Missing GEMINI_API_KEY in environment variables.");
    }

    try {
        console.log(`Calling Nano Banana Pro (Gemini API) with Aspect Ratio: ${aspectRatio}...`);

        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({ 
            model: modelId,
            // @ts-ignore: Experimental parameters for image generation not yet in SDK types
            generationConfig: {
                responseModalities: ["TEXT", "IMAGE"],
                imageConfig: {
                    aspectRatio: aspectRatio,
                    imageSize: "2K" 
                }
            }
        });

        // Helper to fetch and convert URL to Base64
        const urlToPart = async (url: string) => {
            const response = await fetch(url);
            const arrayBuffer = await response.arrayBuffer();
            const base64 = Buffer.from(arrayBuffer).toString('base64');
            const mimeType = response.headers.get('content-type') || 'image/png';
            return {
                inlineData: {
                    data: base64,
                    mimeType
                }
            };
        };

        console.log("Fetching image assets...");
        const [baseImagePart, logoImagePart] = await Promise.all([
            urlToPart(baseImageUrl),
            urlToPart(logoUrl)
        ]);

        // 1. Prepare Inputs
        // The 'prompt' variable contains either the custom product instruction or a default instruction.
        const fullPrompt = `Generate a photorealistic 2K product shot. ${prompt} Important: Keep the provided design/logo unchanged, preserving its colors, text, and details exactly as they appear. Apply it realistically to the surface. Ensure high quality, detailed texture, and realistic lighting.`;
        
        console.log("Sending request to model with images...");

        // 2. Call API
        // Pass the text prompt AND the image parts
        const result = await model.generateContent([
            fullPrompt,
            baseImagePart,
            logoImagePart
        ]);
        const response = await result.response;

        // 3. Extract Image
        // We'll inspect the response structure. 
        // If it's standard text generation, it returns text.
        // If it's image generation, it usually returns inlineData.

        console.log("Model response candidates:", response.candidates);

        const parts = response.candidates?.[0]?.content?.parts;
        const imagePart = parts?.find((part: any) => part.inlineData);

        if (!imagePart || !imagePart.inlineData) {
            // If no image part, maybe it returned text saying it can't do it?
            const textPart = parts?.find((part: any) => part.text);
            if (textPart) {
                console.warn("Model returned text instead of image:", textPart.text);
                throw new Error("Model returned text: " + textPart.text);
            }
            throw new Error("No image generated by the model.");
        }

        const base64Image = imagePart.inlineData.data;
        const mimeType = imagePart.inlineData.mimeType || 'image/png';

        return {
            success: true,
            mockUrl: `data:${mimeType};base64,${base64Image}`
        };

    } catch (error: any) {
        console.error("Gemini API Error:", error);
        return {
            success: false, // Let the frontend show the error
            error: error.message || "Unknown error"
        };
    }
};
